### ISSUE TITLE
Docker File Apearing with Two slashes // In Python_flask_app

### ISSUE THREAD

**Issue by mab3321** [GoogleCloudPlatform/cloud-build-samples#234]
Docker File Apearing with Two slashes // and CI/CD PipeLine Fails.
Step #1: invalid argument "us-central1-docker.pkg.dev/disney-a2b9f//myimage:9f694e1" for "-t, --tag" flag: invalid reference format
Temorarily removed one slash from Cloud-build.yaml

**Comment by glasnt** [comment]
HI @mab3321. 

Based on https://github.com/GoogleCloudPlatform/cloud-build-samples/blob/main/python-example-flask/cloudbuild.yaml: 

```

  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 
           'us-central1-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY_REPO}/myimage:${SHORT_SHA}', '.']
```

Since you have your project ID and "myimage" appearing, you haven't specified a value for `_ARTIFACT_REGISTRY_REPO`, which is resulting in the error. 

For this example, you will need to create a [registry for containers](https://cloud.google.com/artifact-registry/docs/docker/store-docker-container-images#create), then add the name you used for this registry in the command to run this built. 

`gcloud builds submit --substitutions  _ARTIFACT_REGISTRY_REPO=containers` (for example)
